global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9797','host.docker.internal:9798','host.docker.internal:9799','host.docker.internal:9800','host.docker.internal:9801','host.docker.internal:9802']
